#!/usr/bin/env python3
"""Embed registry.json + prompts.json into data.js.

The four HTML surfaces fetch the JSON normally over http. Opened straight from
the filesystem (file://) fetch is blocked by CORS, so they fall back to the
copies in this file and keep working. Regenerate whenever either JSON changes.
"""
import json, os
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__))); os.chdir(ROOT)

reg=json.load(open('registry.json'))
pr=json.load(open('prompts.json'))
open('data.js','w').write(
 "/* GENERATED by tools/gen-data.py — do not edit.\n"
 "   Offline fallback for reference.html / docs.html / prompts.html / index.html\n"
 "   so they work when opened directly from the filesystem. */\n"
 "window.__CW_REGISTRY__ = " + json.dumps(reg, separators=(',',':')) + ";\n"
 "window.__CW_PROMPTS__ = "  + json.dumps(pr,  separators=(',',':')) + ";\n")
print(f"data.js written — {len(reg['components'])} components, "
      f"{sum(len(g['prompts']) for g in pr['groups'])} prompts, "
      f"{os.path.getsize('data.js')//1024} KB")
